name: Daily Commit
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Just need write permission for repo contents
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Make a small change
        run: |
          echo "Last updated: $(date)" > daily_update.txt
          
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_update.txt
          git commit -m "Daily update: $(date)"
          git push
